apiVersion: v1
kind: ResourceQuota
metadata:
  name: quota-small
spec:
  hard:
    # resource quotas
    requests.cpu: "1"
    requests.memory: 1Gi

    # do not specify cpu limits:
    # https://home.robusta.dev/blog/stop-using-cpu-limits
    # limits.cpu: "1"

    limits.memory: 2Gi
