apiVersion: v1
kind: LimitRange
metadata:
  name: default-limitrange
spec:
  limits:
  - defaultRequest: # this section defines default requests
      cpu: 128m
      memory: 128Mi
    default:
      memory: 500Mi
    type: Container
