apiVersion: v1
kind: ResourceQuota
metadata:
  name: quota-large
spec:
  hard:
    # resource quotas
    requests.cpu: "4"
    requests.memory: 4Gi

    # do not specify cpu limits:
    # https://home.robusta.dev/blog/stop-using-cpu-limits
    # limits.cpu: "1"

    limits.memory: 8Gi
