apiVersion: v1
kind: ResourceQuota
metadata:
  name: quota-objects
spec:
  hard:
    configmaps: "100"
    persistentvolumeclaims: "100"
    pods: "100"
    replicationcontrollers: "100"
    secrets: "100"
    services: "100"
